# Generated by Django 4.2.5 on 2023-11-01 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificante',
            fields=[
                ('certificante_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('provincias', models.ManyToManyField(related_name='certificantes_provinciales', to='usuarios.provincias')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificante',
                'db_table': 'certificantes',
            },
        ),
    ]
