# Generated by Django 4.2.5 on 2023-11-10 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=200)),
                ('nombre_representativo', models.CharField(max_length=200)),
                ('solidario', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EspacioObligado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='EN PROCESO', max_length=100)),
                ('motivo', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cant_personas_externas', models.IntegerField(default=0)),
                ('superficie', models.IntegerField(default=0)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('cant_personal', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('personal_capacitado', models.BooleanField(default=False)),
                ('senaletica', models.BooleanField(default=False)),
                ('protocolo_accion', models.BooleanField(default=False)),
                ('sistema_emergencia', models.BooleanField(default=False)),
                ('deas_decreto', models.IntegerField(default=0)),
                ('deas_registrados', models.ManyToManyField(blank=True, to='espacios_obligados.dea')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.entidad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.provincias')),
                ('representantes', models.ManyToManyField(to='usuarios.representante')),
                ('responsables', models.ManyToManyField(blank=True, related_name='responsables', to='espacios_obligados.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('certificante_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.certificante')),
                ('espacio_obligado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.espacioobligado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('estado', models.TextField(blank=True, default='')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.entidad')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.representante')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede')),
            ],
        ),
        migrations.AddField(
            model_name='responsable',
            name='sede_asignada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede'),
        ),
        migrations.CreateModel(
            name='HistorialDEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('servicio', models.CharField(max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('dea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.dea')),
            ],
        ),
        migrations.AddField(
            model_name='espacioobligado',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede'),
        ),
        migrations.AddField(
            model_name='dea',
            name='dea_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede'),
        ),
    ]
