# Generated by Django 4.2.5 on 2023-10-29 22:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobacion_ANMAT', models.BooleanField(default=False)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=200)),
                ('nombre_representativo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cant_personas_externas', models.IntegerField(default=0)),
                ('superficie', models.IntegerField(default=0)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('cant_personal', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('personal_capacitado', models.BooleanField(default=False)),
                ('senaletica', models.BooleanField(default=False)),
                ('protocolo_accion', models.BooleanField(default=False)),
                ('sistema_emergencia', models.BooleanField(default=False)),
                ('deas_decreto', models.IntegerField(default=0)),
                ('deas_registrados', models.ManyToManyField(blank=True, to='espacios_obligados.dea')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.entidad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.provincias')),
                ('representantes', models.ManyToManyField(to='usuarios.representante')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('servicio', models.CharField(max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('dea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.dea')),
            ],
        ),
        migrations.CreateModel(
            name='EspacioObligado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='EN PROCESO', max_length=100)),
                ('motivo', models.TextField(blank=True, default='')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede')),
            ],
        ),
        migrations.AddField(
            model_name='dea',
            name='dea_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede'),
        ),
    ]
