# Generated by Django 4.2.5 on 2023-11-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacios_obligados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dea',
            name='aprobacion_ANMAT',
        ),
        migrations.AddField(
            model_name='dea',
            name='solidario',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('sede_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede')),
            ],
        ),
        migrations.AddField(
            model_name='sede',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='responsables', to='espacios_obligados.responsable'),
        ),
    ]
