# Generated by Django 4.2.5 on 2023-11-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_certificante'),
        ('espacios_obligados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='certificante_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.certificante'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='espacio_obligado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.espacioobligado'),
        ),
    ]
