# Generated by Django 4.2.5 on 2023-11-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('espacios_obligados', '0002_remove_dea_aprobacion_anmat_dea_solidario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.entidad')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.representante')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_obligados.sede')),
            ],
        ),
    ]
