# Generated by Django 4.2.5 on 2023-11-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios_obligados', '0003_solicitudaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaprobacion',
            name='estado',
            field=models.TextField(blank=True, default=''),
        ),
    ]
